version: '3.7'
services:
  futbol-dev:
    container_name: app-futbol-dev
    restart: always
    build:
      context: .
      target: development
    command: npm run start:dev
    ports:
      - 3000:3000
      - 3100:3100
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  futbol-prod:
      container_name: app-futbol-prod
      restart: always
      build:
        context: .
        target: production
      ports:
        - 3000:3000
      env_file:
        - .env
      volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
