version: '3.7'
services:
  api-rest-dev:
    container_name: app-futbol-dev
    restart: always
    build:
      context: ./apiRest
      target: development
    command: npm run start:dev
    ports:
      - 3000:3000
      - 3100:3100
    env_file:
      - ./apiRest/.env
    volumes:
      - ./apiRest:/usr/src/app
      - /usr/src/app/node_modules
  bot-telegram:
      container_name: app-futbol-bot-telegram
      restart: always
      build:
        context: ./botTelegram
      ports:
        - 8443:8443
      env_file:
        - ./botTelegram/.env
      volumes:
        - ./botTelegram:/usr/src/app
        - /usr/src/app/node_modules
  mongo:
    image: mongo
    restart: always
